### ISSUE TITLE
RuntimeError x = x.view(batch, 2*self.channel_size)

### ISSUE THREAD

**Issue by wfeidan** [Cheneng/DPCNN#1]
while x.size()[-2] > 2:
            x = self._block(x)
x = x.view(batch, 2*self.channel_size)

when  x.size()][-2] = 3，then last result x.size()][-2] = 1， so  x = x.view(batch, 2*self.channel_size） error

**Comment by lianghaoqiang** [comment]
def forward(self, x):
        batch = x.shape[0]

        # Region embedding
       --> x = self.conv_region_embedding(x)        # [batch_size, channel_size, length, 1]

        x = self.padding_conv(x)                      # pad保证等长卷积，先通过激活函数再卷积
        x = self.act_fun(x)

there should be a padding_conv(x) before region_embedding(x)

region_embedding操作改变了length的长度，所以在此之前应该进行一次padding_conv(x)操作

**Comment by lianghaoqiang** [comment]
annother error  :  self.padding_pool = nn.ZeroPad2d((0, 0, 0, 1))

right:       self.padding_pool = nn.ZeroPad2d((0, 0, 1, 1))

我瞎改的，反正改了就能跑了（
